config/routes.rb
Sitieitor::Application.routes.draw do
  resources :possible_dates

  root to: "StaticPages#index"

  match "about" => "StaticPages#about"

  match "help" => "StaticPages#help"

  resources :events

  resources :places

  resources :users

end

app/models/possible_date.rb
class PossibleDate < ActiveRecord::Base
  attr_accessible :date_from, :date_to, :event_id
  
  belongs_to :event
end

app/controllers/possible_dates_controller.rb
class PossibleDatesController < ApplicationController
  # GET /possible_dates
  # GET /possible_dates.json
  def index
    @possible_dates = PossibleDate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @possible_dates }
    end
  end

  # GET /possible_dates/1
  # GET /possible_dates/1.json
  def show
    @possible_date = PossibleDate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @possible_date }
    end
  end

  # GET /possible_dates/new
  # GET /possible_dates/new.json
  def new
    @possible_date = PossibleDate.new
    @events = @current_user.events

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @possible_date }
    end
  end

  # GET /possible_dates/1/edit
  def edit
    @possible_date = PossibleDate.find(params[:id])
    @events = @current_user.events
  end

  # POST /possible_dates
  # POST /possible_dates.json
  def create
    @possible_date = PossibleDate.new(params[:possible_date])
    @possible_date.event_id = params[:event][:id]

    respond_to do |format|
      if @possible_date.save
        format.html { redirect_to @possible_date, notice: 'Possible date was successfully created.' }
        format.json { render json: @possible_date, status: :created, location: @possible_date }
      else
        format.html { render action: "new" }
        format.json { render json: @possible_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /possible_dates/1
  # PUT /possible_dates/1.json
  def update
    @possible_date = PossibleDate.find(params[:id])
    @possible_date.event_id = params[:event][:id]

    respond_to do |format|
      if @possible_date.update_attributes(params[:possible_date])
        format.html { redirect_to @possible_date, notice: 'Possible date was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @possible_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /possible_dates/1
  # DELETE /possible_dates/1.json
  def destroy
    @possible_date = PossibleDate.find(params[:id])
    @possible_date.destroy

    respond_to do |format|
      format.html { redirect_to possible_dates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/possible_dates_helper.rb
module PossibleDatesHelper
end

app/views/possible_dates/_form.html.erb
<%= form_for(@possible_date) do |f| %>
  <% if @possible_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@possible_date.errors.count, "error") %> prohibited this possible_date from being saved:</h2>

      <ul>
      <% @possible_date.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label "event_id", "Event" %>
    <%= collection_select(:event, :id, @events, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :date_from %><br />
    <%= f.datetime_select :date_from %>
  </div>
  <div class="field">
    <%= f.label :date_to %><br />
    <%= f.datetime_select :date_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/possible_dates/edit.html.erb
<h1>Editing possible_date</h1>

<%= render 'form' %>

<%= link_to 'Show', @possible_date %> |
<%= link_to 'Back', possible_dates_path %>

app/views/possible_dates/index.html.erb
<h1>Listing possible_dates</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Date from</th>
    <th>Date to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @possible_dates.each do |possible_date| %>
  <tr>
    <td><%= possible_date.event_id %></td>
    <td><%= possible_date.date_from %></td>
    <td><%= possible_date.date_to %></td>
    <td><%= link_to 'Show', possible_date %></td>
    <td><%= link_to 'Edit', edit_possible_date_path(possible_date) %></td>
    <td><%= link_to 'Destroy', possible_date, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Possible date', new_possible_date_path %>

app/views/possible_dates/new.html.erb
<h1>New possible_date</h1>

<%= render 'form' %>

<%= link_to 'Back', possible_dates_path %>

app/views/possible_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @possible_date.event_id %>
</p>

<p>
  <b>Date from:</b>
  <%= @possible_date.date_from %>
</p>

<p>
  <b>Date to:</b>
  <%= @possible_date.date_to %>
</p>


<%= link_to 'Edit', edit_possible_date_path(@possible_date) %> |
<%= link_to 'Back', possible_dates_path %>